###
GET http://localhost:5000/api

###
GET http://localhost:5000/api/getAll

###
POST http://localhost:5000/api/create
Content-Type: application/json

{
    "full" : "https://www.msn.com"
}

###
POST http://localhost:5000/api/create
Content-Type: application/json

{
    "full" : "https://www.ail.com",
    "short" : "res"
}

###
DELETE http://localhost:5000/api/delete
Content-Type: application/json

{
    "short" : "SJbEXC9J5"
}